;Faça um programa que contabiliza todos os valores armazenados em um 
;vetor de 20 posições que sejam pares, maiores que 50 e menores que 100. 

LDR X #0	;LOAD NO ÍNDICE
LDR B #21 	;CARREGA 21 NO REGISTRADOR B PRA CONTROLAR O VETOR
		
DENOVO:		;VAI PRO PRÓX. VALOR
SUB B #1	;DECREMENTADOR DE B, QUE QUANDO B = 0 -> JZ HLT
JZ FIM		;SE = 0, ACABOU O VETOR
LDR A 129, X 	;LOAD DO CONTEÚDO DO ENDEREÇO 129+X EM A
				;INICIO DA LISTA 
ADD X #2		;ADD +2 NO ÍNDICE

PAR:
STR A 127	;PUSH MANUAL (GUARDA O VALOR DO A NO END. 127)
AND A #1	;FAZ O AND DE A COM 1 PRA SABER SE É PAR
JZ MAIOR	;É PAR SE O RESULT. DO AND FOR 0
JMP DENOVO	;SE O RESULT. DE AND FOR 1, PULA PRO PRÓX. VALOR DO VETOR

MAIOR:
LDR A 127	;CARREGA O VALOR DO A ANTES DA FUNC. "PAR" ESTRAGAR ELE
SUB A #50	;TESTA A-50
JN DENOVO	;SE = NEG., NÃO SERVE
JZ DENOVO	;SE = 0, NÃO SERVE

MENOR:
LDR A 127	;CARREGA NOVAMENTE O VALOR DO A ANTES DA FUNC. "PAR" ESTRAGAR ELE
SUB A #100	;TESTA A-100
JZ DENOVO	;SE = 0, NÃO SERVE

LDR A 126	;CONTADOR
ADD A #1
STR A 126	
JMP DENOVO	;DEPOIS DE TUDO FEITO, TESTE O PROX NUM

FIM:
HLT

ORG 128		;DEF. DOS BYTES DO VETOR
DW 16		;DW = DB PULANDO DE 1 EM 1 (COLOCA 0 NO MEIO)
DW 35
DW 31
DW 75
DW 44
DW 72		;PRIMEIRO NUM. A SER TESTADO
DW 100
DW 59
DW 27
DW 43
DW 0
DW 93
DW 98
DW 43
DW 98
DW 91
DW 38
DW 64
DW 49
DW 82